name: CI
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: drone-colcon-workspace/src

      - name: Update submodules recursively
        working-directory: drone-colcon-workspace/src
        run: |
          git submodule update --init --recursive 
          git submodule update --remote

      - name: Update Dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          sudo pip3 install kconfiglib
          sudo apt update

      - name: Build
        shell: bash
        working-directory: drone-colcon-workspace
        run: |
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y --skip-keys -v
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=RELWITHDEBINFO --symlink-install

  test:
    name: Test
    needs: build
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: drone-colcon-workspace/src
          
      - name: Update submodules recursively
        working-directory: drone-colcon-workspace/src
        run: |
          git submodule update --init --recursive 
          git submodule update --remote

      - name: Update Dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          sudo pip3 install kconfiglib
          sudo apt-get install clang-tidy -y
          sudo apt update

      - name: Colcon Test
        shell: bash
        working-directory: drone-colcon-workspace
        run: |
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y --skip-keys -v
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=RELWITHDEBINFO --symlink-install
          colcon test --packages-skip-regex (?i)(px4).* && colcon test-result --verbose

  cpp_linting:
    name: C++ Linting
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run Uncrustify
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          touch external/AMENT_IGNORE
          ament_uncrustify -c ament_code_style.cfg

  python_linting:
    name: Python Linting
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run flake8
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          ament_flake8 --exclude external

  build_linting:
    name: Build Linting
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run ament_lint_cmake
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          touch external/AMENT_IGNORE
          ament_lint_cmake
