name: CI
on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, closed ]
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: drone-colcon-workspace/src

      - name: Update submodules recursively
        working-directory: drone-colcon-workspace/src
        run: |
          git submodule update --init --recursive 
          git submodule update --remote

      - name: Update Dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          sudo pip3 install kconfiglib
          sudo apt-get update
          sudo snap install micro-ros-agent

      - name: Build
        shell: bash
        working-directory: drone-colcon-workspace
        run: |
          # sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          # bash ./src/external/PX4-Autopilot/Tools/setup/ubuntu.sh --no-nuttx
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y --skip-keys -v
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=RELWITHDEBINFO --symlink-install

  test:
    name: Test
    needs: build
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: drone-colcon-workspace/src

      - name: Colcon Test
        shell: bash
        working-directory: drone-colcon-workspace
        run: |
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
          colcon build && colcon test && colcon test-result --verbose

  cpp_linting:
    name: C++ Linting
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run Uncrustify
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          touch external/AMENT_IGNORE
          # ament_uncrustify -c ament_code_style.cfg

  python_linting:
    name: Python Linting
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update Dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt-get update

      - name: Run flake8
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          ament_flake8 --exclude external
  
  build_linting:
    name: Build Linting
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run ament_lint_cmake
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          touch external/AMENT_IGNORE
          # ament_lint_cmake